use ecommerce_project;
select * from customers ; 
select * from orders;
select * from order_items;
select * from products ; 
select * from payments ;

-- 1  Calculate the total revenue generated by the company across all orders.
select sum(price) from order_items ; 

-- 2  Determine the total number of orders and total number of customers.
select count(*) from customers;
select count(*) from orders;

-- 3 Calculate the average order value (AOV).
select AVG(total_revenue) as avg_order_value
from (
select order_id, sum(price) as total_revenue
from order_items
group by order_id
 ) as t ;
 
-- 4  Compute the total spending for each customer and identify the top 10 customers by revenue.
select customers.customer_id,  sum(order_items.price) as total_revenue
from customers
inner join orders on customers.customer_id = orders.customer_id
inner join order_items on orders.order_id = order_items.order_id
group by customer_id order by total_revenue desc limit 10 ;

-- 5  Identify repeat customers (customers who have placed more than one order).
select customers.customer_id , count(orders.order_id) as total_count 
from customers 
inner join orders on customers.customer_id = orders.customer_id
group by customer_id  
order by total_count desc limit 10 ;

-- 6. Calculate the total value of each order and identify the highest value orders
select orders.order_id , sum(order_items.price) as total_revenue 
from orders 
inner join order_items on orders.order_id=order_items.order_id 
group by order_id order by total_revenue desc ;

-- 7. Identify the 	most frequently sold products based on the number of sales.
select product_id , count(product_id) as quantity 
from order_items 
group by product_id 
order by quantity desc limit 10  ;

-- 8. Identify 	the top revenue-generating products.
select product_id , sum(price) as revenue_generating
from order_items 
group by product_id 
order by revenue_generating desc limit 10  ;

-- 9. Analyze revenue contribution by city and state.
select customers.city , customers.state ,  sum(order_items.price) as total_revenue
from customers
inner join orders on customers.customer_id = orders.customer_id
inner join order_items on orders.order_id = order_items.order_id
group by city ,state limit 10 ;

-- 10. Identify the top-performing cities and states based on total revenue and order count.
select customers.city , customers.state ,  sum(order_items.price) as total_revenue , count(distinct orders.order_id) as total_count 
from customers
inner join orders on customers.customer_id = orders.customer_id
inner join order_items on orders.order_id = order_items.order_id
group by city ,state order by total_revenue desc ,total_count desc  limit 10 ;

-- 11. Perform a monthly analysis of orders and revenue to identify trends over time.
select month(str_to_date(orders.`Order date`, '%Y-%m-%d')) as months,  sum(order_items.price) as total_revenue , count(distinct orders.order_id) as total_count 
from orders
inner join order_items on orders.order_id = order_items.order_id
group by months  order by total_revenue desc ,total_count desc ;

-- 12. Identify the month with the highest sales performance.
select month(str_to_date(orders.`Order date`, '%Y-%m-%d')) as months,  sum(order_items.price) as highest_sale
from orders
inner join order_items on orders.order_id = order_items.order_id
group by months  order by highest_sale desc limit 1 ;

-- 13. Calculate the order frequency per customer.
select customers.customer_id , count(orders.order_id) as total_count 
from customers 
inner join orders on customers.customer_id = orders.customer_id
group by customer_id
order by total_count desc  ;

-- 14. Analyze customer segments based on spending behavior (high, medium, low value customers).
select 
    segment,
    count(*) as total_customers
from
(
    select 
        customers.customer_id,
        case
            when sum(order_items.price) > 3000 then 'High'
            when sum(order_items.price) > 1000 then 'Medium'
            else 'Low'
        end as segment
    from customers
    inner join orders on customers.customer_id = orders.customer_id
    inner join order_items on orders.order_id = order_items.order_id
    group by customers.customer_id
) as t
group by segment;

-- 15. Analyze payment methods: Most frequently used payment type
select payment_type,count(payment_type) as count_payment from payments group by payment_type order by count_payment desc; 

-- 16. Analyze payment methods: Revenue contribution by payment type
select payment_type , sum(payment_value) as payment_revenue from payments group by payment_type order by payment_revenue desc; 

-- 17. Calculate the average number of items per order (basket size)
select avg(total_count) as avg_product_id from (
select order_id , count(product_id) as total_count from order_items group by order_id) as t ; 

-- 18. Identify the highest value order
select order_id , sum(price) as total_price from order_items group by order_id order by total_price desc limit 1 ;

-- 19. Identify the lowest value order
select order_id , sum(price) as total_price from order_items group by order_id order by total_price asc limit 1  ;

-- 20. Analyze customer distribution across regions (state-wise analysis)
select state , count(customer_id) as total_customer from customers group by state order by total_customer desc limit 10 ; 